# Configuration Document
# https://github.com/zeke/semantic-pull-requests#configuration

# Always validate all commits, and ignore the PR title
commitsOnly: true

# By default types specified in commitizen/conventional-commit-types is used.
# See: https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json
# You can override the valid types
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  - package
